# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e348c0e43c43ce6a692d9f1d7a997d1c9d630d97d1e8a28269da53bab7417d8714cef82f1976449c5be486296f3f565522ac368af8b03d790b47304b4608c2ce

test:
  secret_key_base: add00c4a9a703cb2f9ee2f7511cbf3135700a02861242ec0a9f08a692b4cf59dda3582ab30aa998325d086024de09ef02f2797305b6caff5408eaff5c12d9f1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
